### PR TITLE
Improve error messages for regular expressions

### PR DESCRIPTION
**Pull request by urso**
Improve regexp error messages by including the reason compilation failed

### CODE REVIEW

**Comment by ruflin** [comment]
Tests seem to fail on Golang 1.5 (tip). Not sure if you need "tip" in the builds?

**Comment by ruflin** [comment]
LGTM

**Comment by urso** [comment]
tip is go development branch (next 1.7). The message about go1.5 vendoring you will find in any release 1.5+

**Comment by urso** [comment]
I think it's a problem with travis. The dependency is required for testing only (ucfg tries not to have any dependencies). That is one has to do `go get -t -v ./...` before `go test ./...`. This is the case for go 1.5 and 1.6, but not for tip.

**Pull request merged**
