### PR TITLE
Variable expansion with environments

### PR DESCRIPTION
**Pull request by urso**

### CODE REVIEW

**Comment by urso** [comment]
- pass additional configurations for variable lookup
- add support for variable expansion callbacks used if path has not been found
  in config itself or in additional configurations passed for lookup
- add ResolveEnv option using os.Getenv for variable expansion if path can not
  be resolved

**Comment by ruflin** [comment]
I'm trying to get my head around this one and I'm not 100% sure yet what the consequences of this PR are. Could you give an example of a yml config option that is possible after but isn't possible now?

Code change wise I got the impression that we pass `opts *options` in way too many places. Couldn't we perhaps simplify some of the code and passing params by making it part of some objects. I don't have a specific suggestion, this is more a question.

**Comment by urso** [comment]
The options kind of acts like evaluation environment/context telling ucfg how to process merging and unpacking. Due to variable expansion (not being based on regex of input file) adding some minimal of evaluation supports (by nature), we need to pass the run environment down to the bottom nodes of our computations. Some new fields in options are now required by path evaluators (see `path.go`) iterating the config given some path. Due to most structures requiring the environment being precomputed, the environment is passed through.

Having options available in all places will allow us to add options for more strict/weak type checks during conversions (e.g. make support for int/float->time.Duration optional).

Normally it's up to the ucfg user (in this case libbeat) to decide on common settings being passed to Merge and Unpack. Not passing options, but storing them within the config can be difficult in the presence of merging configs with multiple other configs + requires rather big refactoring to ucfg in general.

Some (extreme) use-case for ucfg variable expansion with support for environments is https://github.com/urso/ljtest . ljtest computes the config environment dynamically per test, merging testsuite + test + service configs in one common config.

**Sample use case: environment variable lookup (not possible with ucfg right now)**

```
    config.Unpack(&to, ucfg.ResolveEnv)
```

[ResolveEnv](https://github.com/urso/ucfg/pull/28/files#diff-0cd986ed6644b9d8bc249897c3cb2fbcR53) installs a callback into options.resolver, looking up variables if name is unknown to ucfg.

Difference to beats implementation is: variable expansion in libbeat is based on file-content treated as raw string. expansion can happen at any place potentially breaking the file. Using ResolveEnv variable expansion is limited to config values only.

The generalization is custom name lookup callbacks:

```
    config.Unpack(&to, ucfg.Resolve(customLookup))
```

customLookup can potentially do anything users want (e.g. read configs via etcd or zookeeper, use predefined patterns for common names).

**Sample use case: predefined application specific variables during lookup**

In addition to custom resolvers one can pass additional environments for lookup to ucfg (field envs in options). The environments are of type *ucfg.Config themselves.

Advantages of environments over merging configs:
1. No need to implement custom merge logic, Just pass additional environments for lookup with predefined variables.
2. Config access recording (not yet implemented) records all fields accessed giving ucfg users the chance to report all fields not being read. If common predefined names were to be merged into the config for lookup, they would also be subject to error reporting.
3. compute/pass custom environments based on computation context. E.g. used by ljtest to pass testsuite + test + service configs + full active test config (via `_active` variable) in ljtest without having to rewrite the global config every so often.

e.g. passing common application paths in environments (beats use-case)

```
    pathsEnv, _ := ucfg.NewFrom(map[string]string{
        "path.home": ... ,
        "path.config": "${path.home}/config",
        "path.data": "${path.data}/data",
    }, ucfg.PathSep("."), ucfg.VarExp)

    config.Unpack(&to, ucfg.PathSep("."), ucfg.Env(pathsEnv), ucfg.ResolveEnv)
```

In config file one can use:

```
    registry_file: ${path.data}/registry.json
```

This is currently handled in beats by automatically prepending `${path.data}` in case of registry.json being a relative path (by default ${path.home} might be the current working directory). The configs should be explicit about what happens to configs instead of doing some magic.


Another potential use case regarding multiline support (and regex) in beats:

- common multiline scenarios environment config:

```
multiline.scenarios.java-stack-trace:
  pattern: ...

multiline.scenarios.python-stack-trace:
  pattern: ...

multiline.scenarios.rabbitmq-log:
  pattern: ...
```

- and filebeat config:

```
    multiline:
      - ${multiline.scenarios.java-stack-trace}
      - ${multiline.scenarios.python-stack-trace}
```
This works due to ucfg (already) treating single references on right hand side as references (no string replacement). If any string-splicing happens supported types are limited to numbers and strings and ucfg will generate errors on type mismatch.


All features are opt-in and disabled by default. It's up to the user of ucfg to decide which features will be used.

Already support by ucfg, there are different types of variable expansion operators (inspired by bash):

`${VAR}`: try to expand VAR. Error if `VAR` being unknown
`${VAR:DEFAULT}`: try to expand `VAR`. Use `DEFAULT` if `VAR` is unknown
`${VAR:+ELSE}`: expand to `ELSE` if `VAR` can be resolved. Otherwise expand to empty string
`${VAR:?custom error message}`: Generate custom error message if `VAR` can not be resolved.

In contrast to libbeat current variable expansion support, unknown variables are not expanded into `""`, but an error message will be generated unless one explicitely asks for empty expansion via `${VAR:}`.

**Comment by ruflin** [comment]
Merging as this feature is off by default and it is definitively worth having it in ucfg. We can continue the discussion on enabling or not when updating ucfg in beats.

**Pull request merged**
